### ISSUE TITLE
BICEPS and EBSP: are they comparable?

### ISSUE THREAD

**Issue by forianfinest** [rbouckaert/biceps#2]
Dear all,
I wanted to test BEAST a little and I made BICEPS analyses for two genes with different ploidy. I then used both genes in EBSP (of course, I also set here the ploidy).
For what is my understanding of BEAST, all the plots are in a natural logaritmic scale: so, for example, one suggestion [I saw in a tutorial from Emiliano Trucchi ](http://www.emilianotrucchi.it/images/EBSP_RADseq_tutorial.pdf)is to plot the pop size with log in R with EBSP; e.g.:

plot(data$time, data$mean, log="y", type="l", col=1)

Now, I am wondering: is BICEPS equivalent to EBSP and therefore I have to plot the same kind of data always in a log-scale? I am asking because I also have the original BICEPS plots from Tracer and they would look pretty different from the original, if I set the log-scale in R.

Thanks in advance for the answer and sorry for the bother and for my utter ignorance.

Best wishes,
Mattia

P.s: I also asked this same question in BEAST's Ggroup, without any answer.

**Comment by rbouckaert** [comment]
Hi Mattia, 

Population sizes between different models should be comparable, but BICEPS is not equivalent to EBSP:
o EBSP differs in that population sizes are shared among trees, while in BICEPS each tree gets its own population history. This is a fundamental difference between the two methods.
o the prior on population sizes differs. In general, it is quite hard in practice to make the priors match exactly.

The reason for plotting demographic histories on a log scale is just because there tends to be orders of magnitude difference between lowest and highest values -- just for practical reasons to make the plots more readable.

Hope this helps, Remco

**Comment by forianfinest** [comment]
Dear Dr.  Bouckaert,
thank you very much for your answer! That helps!
Best wishes,
Mattia
